name: ConsoService
description: A web server built using the shelf package.
version: 0.0.1
#homepage: https://www.example.com
#author: Bertrand <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  args: ^0.13.7
  _discoveryapis_commons: '>=0.1.0 <0.2.0'
  http: '>=0.11.1 <0.12.0'
  logging: '>=0.11.1 <0.12.0'
  logging_handlers: ">=0.8.0 <0.9.0"
  rpc: '>=0.5.0 <0.6.0'
  shelf: '>=0.6.0 <0.7.0'
  shelf_route: '>=0.13.4 <0.14.0'
  shelf_rpc: '>=0.0.3 <0.0.4'
  angel_configuration: "^1.1.0"
dev_dependencies:
  test: ^0.12.0
